name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure Git for Deployment
      - name: Configure Git
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"

      # Step 3: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 5: Build the application
      - name: Build Application
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
